import Globales from "./globales";

export default class Errores {
    public static MENSAJES = {
        FALTA_URL: "Es necesario proporcionar la URL que se esta cargando en la clase ServicioCargando",
        CREDENCIALES_ERRONEAS: "Las credenciales insertadas son erróneas, inténtelo de nuevo",
        FORMULARIO_NO_VALIDO: "Formulario erróneo, rellene correctamente los campos antes de continuar",
        ERROR_CONEXION: "Error de conexión no se ha podido conectar con el servidor",
        SESION_CADUCADA: "Su sesión ha caducada, inicie sesión de nuevo",
        AUTENTICACION: "Error de autenticación del usuario",
        ERROR_CENTRO: "No se ha podido obtener informacion del centro",
        ERROR_HORAS_DISPONIBLES: "No se ha podido obtener el listado de horas disponibles",
        ERROR_DIAS_DISPONIBLES: "No se ha podido obtener el listado de dias disponibles",
        ERROR_PRUEBAS_RECOMENDADAS_PACIENTE: "No se ha podido obtener el listado de pruebas recomendadas",
        ERROR_FORMULARIO: "Rellene todos los campos del formulario antes de continuar",
        ERROR_SOLICITAR_CITA: "Se ha producido un error al solicitar la cita",
        ERROR_DOCUMENTO: "No se ha podido obtener el documento solicitado",
        ERROR_LISTADO_CITAS: "No se ha podido obtener el listado de citas",
        ERROR_LISTADO_CENTROS: "No se ha podido obtener el listado de centros",
        ERROR_LISTADO_PRUEBAS_COMPLEMENTARIAS: "No se ha podido obtener el listado de pruebas complementarias",
        ERROR_BORRAR_CITA: "Se ha producido un error al tratar de eliminar su cita",
        ERROR_INFO_PRUEBA: "No se ha podido obtener informacion de la prueba seleccionada",
        ERROR_INFO_PACIENTE: "No se ha podido obtener informacion del paciente seleccionado",
        ERROR_INFO_CITA: "No se ha podido obtener informacion de la cita seleccionada",
        ERROR_GESTIONAR_CITA: "No se ha podido guardar la gestión de la cita correctamente",
        ERROR_LISTADO_EMPLEADOS: "No se ha podido obtener el listado de empleados de la plantilla",
        ERROR_ELIMINAR_EMPLEADO: "Se ha producido un error al tratar de eliminar el empleado",
        ERROR_INFO_EMPLEADO: "No se ha podido obtener informacion del empleado seleccionado",
        ERROR_CANDIDATO_ES_EMPLEADO: "El candidato solicitado ya es empleado de este centro",
        ERROR_ANNADIR_EMPLEADO: "No se ha podido añadir el empleado solicitado al centro",
        ERROR_ACTUALIZAR_EMPLEADO: "No se ha podido actualizar la informacion del empleado seleccionado",
        ERROR_LISTADO_PRUEBAS_EMPLEADO: "No se ha podido obtener el listado de pruebas complementarias que puede tratar el empleado seleccionado",
        ERROR_LISTADO_PRUEBAS_CENTRO: "No se ha podido obtener el listado de pruebas complementarias disponibles en su centro",
        ERROR_SIN_CANDIDATO_VALIDO: "Seleccione un candidato con un número de seguridad social válido antes de continuar",
        ERROR_CANDIDATO_SIN_PRUEBAS: "Seleccione al menos una prueba complementaria que pueda tratar el candidato",
        ERROR_EMPLEADO_SIN_PRUEBAS: "Seleccione al menos una prueba complementaria que pueda tratar el empleado",
        ERROR_ELIMINAR_PRUEBA_CENTRO: "Se ha producido un error al tratar de eliminar la prueba del centro",
        ERROR_HORARIOS_PRUEBA_CENTRO: "Se ha producido un error al tratar de obtener los horarios de la prueba en centro",
        ERROR_ANNADIR_PRUEBA_CENTRO: "No se ha podido añadir la prueba solicitada al centro",
        ERROR_ACTUALIZAR_PRUEBA_CENTRO: "No se ha podido actualizar los horarios de la prueba seleccionada para el centro",
        ERROR_NOMBRE_CENTRO: "No se ha podido obtener el nombre del centro del administrador",
        ERROR_LISTADO_CENTROS_COMUNIDAD: "No se ha podido obtener el listado de centros de la comunidad",
        ERROR_ELIMINAR_CENTRO: "Se ha producido un error al tratar de eliminar el centro seleccionado",
        ERROR_LISTADO_ADMINISTRADORES_CENTRO: "No se ha podido obtener el listado de administradores del centro solicitado",
        ERROR_INFO_ADMINISTRADOR: "No se ha podido obtener informacion del administrador seleccionado",
        ERROR_ANNADIR_CENTRO: "No se ha podido añadir el centro solicitado a la comunidad",
        ERROR_ACTUALIZAR_CENTRO: "No se ha podido actualizar la informacion del centro de la comunidad seleccionado",
        CENTRO_SIN_ADMINISTRADORES: "El centro debe tener al menos un administrador para poder continuar",
        ERROR_SOLICITAR_IMAGENES_CENTRO: "No se han podido obtener las imagenes del centro solicitado",
        ERROR_SUBIR_IMAGENES_CENTRO: "Se ha producido un error al subir las imagenes del centro",
        ERROR_IMAGEN_DEMASIADO_GRANDE: "El tamaño máximo permitido es de "+Globales.MAXIMO_TAMAÑO_IMAGEN / 1048576+"MB por imagen",
        ERROR_IMAGEN_YA_SELECCIONADA: "La imagen que quiere seleccionar ya existe",
        ERROR_MAXIMO_IMAGENES: "El máximo de imagenes permitidas es: "+Globales.MAXIMO_IMAGENES_CENTRO,
        ERROR_LISTADO_CARPETAS_PRUEBAS: "No se ha podido obtener el listado de carpetas de pruebas de la comunidad",
        ERROR_ANNADIR_CARPETA_PRUEBAS: "Se ha producido un error al tratar de añadir la carpeta de pruebas seleccionada",
        ERROR_ACTUALIZAR_CARPETA_PRUEBAS: "Se ha producido un error al tratar de actualizar la carpeta de pruebas seleccionada",
        ERROR_ELIMINAR_CARPETA_PRUEBAS: "Se ha producido un error al tratar de eliminar la carpeta de pruebas seleccionada",
        ERROR_LISTADO_PRUEBAS_COMUNIDAD: "No se ha podido obtener el listado de carpetas de pruebas de la comunidad",
        ERROR_ELIMINAR_PRUEBA_COMUNIDAD: "Se ha producido un error al tratar de eliminar la carpeta de pruebas seleccionada",
        ERROR_ANNADIR_PRUEBA: "Se ha producido un error al tratar de añadir la prueba seleccionada",
        ERROR_ACTUALIZAR_PRUEBA: "Se ha producido un error al tratar de actualizar la prueba seleccionada",
        ERROR_RANGOS_EDAD_PRUEBA: "Se ha producido un error al obtener el listado de rangos de edad de la prueba seleccionada",
    };
    
    public static CODIGOS_BACK = {
        TOKEN_EXPIRADO: {codigo: 'token_expirado.error', mensaje: this.MENSAJES.SESION_CADUCADA},
        AUTENTICACION: {codigo: 'autenticacion.error', mensaje: this.MENSAJES.AUTENTICACION},
    };
}